/* global React */
// Mock data — estrutura baseada em packages/shared/src/types/equipment.ts + fill/page.tsx

const MOCK_DOC = {
  id: 'doc_2026_abr_18',
  name: 'Preventiva Loja 042 — Abril/2026',
  templateName: 'Checklist Preventiva PDV',
  status: 'in_progress',
  loja: 'Mercado Central — Loja 042',
  setorSelecionado: null, // filtro
  totalItems: 18,
  completedItems: 7,
  // Setores disponíveis (derivados de assignments)
  setores: [
    { id: 's1', nome: 'Frente de Caixa', count: 8, done: 5 },
    { id: 's2', nome: 'Balcões e Pesagem', count: 4, done: 2 },
    { id: 's3', nome: 'Retaguarda', count: 3, done: 0 },
    { id: 's4', nome: 'Padaria', count: 3, done: 0 },
  ],
  // Assignments — um por equipamento
  assignments: [
    {
      idx: 0,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-01',
      serie: 'SN-7781-A',
      status: 'done',
    },
    {
      idx: 1,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-02',
      serie: 'SN-7782-A',
      status: 'done',
    },
    {
      idx: 2,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-03',
      serie: 'SN-7783-A',
      status: 'done',
    },
    {
      idx: 3,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'Impressora',
      iconKey: 'printer',
      numeroEquipamento: 'IMP-01',
      serie: 'BX-9921',
      status: 'done',
    },
    {
      idx: 4,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'Impressora',
      iconKey: 'printer',
      numeroEquipamento: 'IMP-02',
      serie: 'BX-9922',
      status: 'done',
    },
    {
      idx: 5,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-04',
      serie: 'SN-7784-A',
      status: 'progress',
    },
    {
      idx: 6,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-05',
      serie: 'SN-7785-A',
      status: 'pending',
    },
    {
      idx: 7,
      setorId: 's1',
      setorNome: 'Frente de Caixa',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-06',
      serie: 'SN-7786-A',
      status: 'pending',
    },

    {
      idx: 8,
      setorId: 's2',
      setorNome: 'Balcões e Pesagem',
      tipo: 'Balança',
      iconKey: 'scale',
      numeroEquipamento: 'BAL-01',
      serie: 'TO-4410',
      status: 'done',
    },
    {
      idx: 9,
      setorId: 's2',
      setorNome: 'Balcões e Pesagem',
      tipo: 'Balança',
      iconKey: 'scale',
      numeroEquipamento: 'BAL-02',
      serie: 'TO-4411',
      status: 'done',
    },
    {
      idx: 10,
      setorId: 's2',
      setorNome: 'Balcões e Pesagem',
      tipo: 'Balança',
      iconKey: 'scale',
      numeroEquipamento: 'BAL-03',
      serie: 'TO-4412',
      status: 'pending',
    },
    {
      idx: 11,
      setorId: 's2',
      setorNome: 'Balcões e Pesagem',
      tipo: 'Impressora',
      iconKey: 'printer',
      numeroEquipamento: 'IMP-03',
      serie: 'BX-9923',
      status: 'pending',
    },

    {
      idx: 12,
      setorId: 's3',
      setorNome: 'Retaguarda',
      tipo: 'Impressora',
      iconKey: 'printer',
      numeroEquipamento: 'IMP-04',
      serie: 'HP-2201',
      status: 'pending',
    },
    {
      idx: 13,
      setorId: 's3',
      setorNome: 'Retaguarda',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-07',
      serie: 'SN-7787-A',
      status: 'pending',
    },
    {
      idx: 14,
      setorId: 's3',
      setorNome: 'Retaguarda',
      tipo: 'Balança',
      iconKey: 'scale',
      numeroEquipamento: 'BAL-04',
      serie: 'TO-4413',
      status: 'pending',
    },

    {
      idx: 15,
      setorId: 's4',
      setorNome: 'Padaria',
      tipo: 'Balança',
      iconKey: 'scale',
      numeroEquipamento: 'BAL-05',
      serie: 'TO-4414',
      status: 'pending',
    },
    {
      idx: 16,
      setorId: 's4',
      setorNome: 'Padaria',
      tipo: 'Impressora',
      iconKey: 'printer',
      numeroEquipamento: 'IMP-05',
      serie: 'BX-9924',
      status: 'pending',
    },
    {
      idx: 17,
      setorId: 's4',
      setorNome: 'Padaria',
      tipo: 'PDV',
      iconKey: 'checkout',
      numeroEquipamento: 'PDV-08',
      serie: 'SN-7788-A',
      status: 'pending',
    },
  ],
};

// Campos (TemplateField) — espelha a estrutura do fill/page.tsx
const MOCK_FIELDS = [
  // Auto-populados (readonly, readout do equipamento)
  {
    id: 'f_num',
    type: 'text',
    autoPopulate: true,
    config: { label: 'Nº Equipamento', placeholder: 'PDV-04' },
  },
  {
    id: 'f_ser',
    type: 'text',
    autoPopulate: true,
    config: { label: 'Série', placeholder: 'SN-7784-A' },
  },
  {
    id: 'f_pat',
    type: 'text',
    autoPopulate: true,
    config: { label: 'Patrimônio', placeholder: 'PAT-10284' },
  },
  // Preenchidos pelo técnico
  {
    id: 'f_lig',
    type: 'checkbox',
    config: { label: 'Equipamento liga normalmente?', required: true },
  },
  {
    id: 'f_lim',
    type: 'checkbox',
    config: { label: 'Realizou limpeza externa e interna?', required: true },
  },
  {
    id: 'f_con',
    type: 'checkbox',
    config: { label: 'Conexões e cabos íntegros?', required: true },
  },
  {
    id: 'f_imp',
    type: 'checkbox',
    config: { label: 'Impressão/emissão funcionando?', required: false },
  },
  {
    id: 'f_obs',
    type: 'text',
    config: {
      label: 'Observações',
      placeholder: 'Descreva qualquer problema identificado',
      required: false,
      multiline: true,
    },
  },
  // Fotos
  { id: 'f_ph1', type: 'image', config: { label: 'Foto — antes da preventiva', required: true } },
  { id: 'f_ph2', type: 'image', config: { label: 'Foto — depois da preventiva', required: true } },
  // Assinatura
  {
    id: 'f_sig',
    type: 'signature',
    config: { label: 'Assinatura do responsável da loja', required: true },
  },
];

// Values do equipamento atual (índice 5 = PDV-04, status 'progress')
const MOCK_VALUES = {
  f_num: 'PDV-04',
  f_ser: 'SN-7784-A',
  f_pat: 'PAT-10284',
  f_lig: true,
  f_lim: true,
  f_con: false,
  f_imp: null,
  f_obs: 'Leitor de código de barras com toque intermitente — recomendar substituição.',
  f_ph1: 'before', // placeholder key
  f_ph2: null,
  f_sig: null,
};

Object.assign(window, { MOCK_DOC, MOCK_FIELDS, MOCK_VALUES });
